services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - "3306"
# To Connect mysql database from terminal
# Run this only after spring-boot:run,
# because docker compose dependency turn on the docker only when spring project started running
# docker ps
# docker exec -it <mysql_container_name> mysql -u yourUsername -p
