spring.application.name=easybudget-spring

# These are for local
# spring.datasource.url=jdbc:mysql://localhost:3306/easybudgetdb
# spring.datasource.username=easybudgetadmin
# spring.datasource.password=easybudgetpw
spring.datasource.url=jdbc:sqlserver://easybudget-mysql-server.database.windows.net:1433;database=EasyBudgetMySQL;user=easybudgetmysqladmin@easybudget-mysql-server;password=8*23%#6m8%&!$78U;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
