spring.application.name=easybudget-spring

# These are for local
# spring.datasource.url=jdbc:mysql://localhost:3306/easybudgetdb
# spring.datasource.username=easybudgetadmin
# spring.datasource.password=easybudgetpw

# These are for Azure
# spring.datasource.url=jdbc:mysql://easybudget-mysql-server.database.windows.net/EasyBudgetMySQL
# ;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
# spring.datasource.username=easybudgetmysqladmin
# spring.datasource.password=8*23%#6m8%&!$78U

# Testing with h2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# To executes data.sql after Hibernate initailization,
# By default, data.sql executes before Hibernate initailization
spring.jpa.defer-datasource-initialization=true

# spring.jpa.show-sql: true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
